apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: demo-operator
  template:
    metadata:
      labels:
        name: demo-operator
    spec:
      serviceAccountName: demo-operator
      containers:
        - name: demo-operator
          # image: 172.30.1.1:5000/openshift/demo-operator
          image: eivantsov/demo-operator
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - demo-operator
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "demo-operator"